site_name: UNC Game Dev Club Wiki Documentation
nav:
  - Home: index.md
  - About: about.md
  - Group Projects: group_projects.md
  - Schedule: schedule.md
  - Resources:
    - Programming: programming_resources.md
    - Art: art_resources.md
    - Music: music_resources.md
    - Writing: writing_resources.md
    - Game Design: game_design_resources.md
    - Practice Projects: practice_projects.md
theme:
  name: material
