site_name: UNC Game Dev Club Wiki Documentation
nav:
  - Home: index.md
  - About: about.md
  - Group Projects: group_projects.md
  - Schedule: schedule.md
  - Resources: resources.md
  
theme:
  name: material
