site_name: UNC Game Dev Club Wiki Documentation
nav:
  - Home: index.md
  - About: about.md
  - Group Projects: group_projects.md
  - Schedule: schedule.md
  - Events: events.md
  - Resources:
    - Presentations: presentations.md
    - Practice Projects: practice_projects.md
theme:
  name: material
